services:
  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend

  frontend:
    image: koolcart_f
    deploy:
      mode: replicated
      replicas: 2

  backend:
    image: koolcart_b
    deploy:
      mode: replicated
      replicas: 2