# Server port
server:
  port: 8080
  address: 0.0.0.0

spring:
  # MySQL
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # msgs cloud DB Info
    url: jdbc:mysql://${public_ip}:3306/${db_name}
    username: ${db_id}
    password: ${db_pwd}

  # File Upload
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB

  # JPA
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect

  profiles:
    include: api

# prometheus만 엔드포인트에 접근 가능하게 설정
management:
  endpoints:
    web:
      exposure:
        include: "prometheus"